name: bottom_navigation_scaffold
description: Build bottom navigation layout easier.
repository: https://github.com/anthonychwong/bottom-navigation-scaffold
homepage: https://anthonychwong.netlify.app/
version: 0.0.1-rc2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4

dev_dependencies:

  flutter_test:
    sdk: flutter
